INSERT INTO `team` (`id`, `teamName`, `teamStadium`) VALUES
(1, 'Arsenal', 'Emirates Stadium'),
(2, 'Aston Villa', 'Villa Park'),
(3, 'Bournemouth', 'Vitality Stadium'),
(4, 'Brentford', 'Gtech Community Stadium'),
(5, 'Brighton & Hove Albion', 'Amex Stadium'),
(6, 'Burnley', 'Turf Moor'),
(7, 'Chelsea', 'Stamford Bridge'),
(8, 'Crystal Palace', 'Selhurst Park'),
(9, 'Everton', 'Goodison Park'),
(10, 'Fulham', 'Craven Cottage'),
(11, 'Liverpool', 'Anfield'),
(12, 'Luton Town', 'Kenilworth Road'),
(13, 'Manchester City', 'Etihad Stadium'),
(14, 'Manchester United', 'Old Trafford'),
(15, 'Newcastle United', 'St. James\'' Park'),
(16, 'Nottingham Forest', 'The City Ground'),
(17, 'Sheffield United', 'Bramall Lane'),
(18, 'Tottenham Hotspur', 'Tottenham Hotspur Stadium'),
(19, 'West Ham United', 'London Stadium'),
(20, 'Wolverhampton Wanderers', 'Molineux Stadium');